### ISSUE TITLE
这个在 CSS 文件里怎么使用呢？

### ISSUE THREAD

**Issue by welefen** [stcjs/stc-inline#1]

**Comment by alvarto** [comment]
内置base64小图的功能打开`{datauri: true}`即可。我稍后更新一下README吧

**Comment by welefen** [comment]
要支持设置多大的文件才 base64，因为一般是设置小文件 base64

**Comment by alvarto** [comment]
采用了经验值32768。
IE8无法识别32k以上的base64图片，见https://msdn.microsoft.com/en-us/library/cc848897(v=vs.85).aspx

今晚统一整理到README吧。

**Comment by alvarto** [comment]
Fiexed in 2fe01c74d6ceae70ce4f7c5cd7c44fef5bd25bdc.
